[package]
name = "saji"
version = "0.1.0"
authors = ["Asami Doi"]
edition = "2018"

[dependencies]
liumlib = { path = "../liumlib" }
hashbrown = "0.11"

[lib]
name = "saji"
test = false

[[bin]]
name = "saji"
test = false
