[package]
name = "browser-rs"
version = "0.1.0"
authors = ["Asami Doi"]
edition = "2018"

[dependencies]
liumlib = { path = "../liumlib" }
saji = { path = "../saji" }

[lib]
name = "browser_rs"
test = false

[[bin]]
name = "browser-rs"
test = false
