#!/bin/bash -x
LIUMOS_THIRDPARTY_PATH=`pwd`/third_party
INSTALL_PREFIX=`pwd`/third_party_root

LLVM_BIN_PATH=/usr/local/opt/llvm/bin
NEWLIB_INC_PATH=${LIUMOS_THIRDPARTY_PATH}/newlib-cygwin_dest/include
LLVM_PROJ_PATH=${LIUMOS_THIRDPARTY_PATH}/llvm-project
LIBUNWIND_PATH=${LLVM_PROJ_PATH}/libunwind
LIBCXX_INC_PATH=$LLVM_PROJ_PATH/libcxx/include

SRC_ROOT=${LLVM_PROJ_PATH}/libcxxabi
BUILD_ROOT=${LIUMOS_THIRDPARTY_PATH}_build/libcxxabi
mkdir -p "$BUILD_ROOT" && cd "$BUILD_ROOT" &&
rm CMakeCache.txt ; cmake \
	-DCMAKE_CROSSCOMPILING=True \
	-DCMAKE_SYSTEM_NAME=Generic \
	-DCMAKE_HOST_SYSTEM_NAME=Darwin \
	-DCMAKE_AR=$LLVM_BIN_PATH/llvm-ar \
	-DCMAKE_RANLIB=$LLVM_BIN_PATH/llvm-ranlib \
	-DCMAKE_CXX_COMPILER=$LLVM_BIN_PATH/clang++ \
	-DCMAKE_CXX_FLAGS="-I$NEWLIB_INC_PATH -D__ELF__ -D_LIBUNWIND_IS_BAREMETAL=1 -D_LDBL_EQ_DBL -U__APPLE__ -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION -mcmodel=large" \
	-DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
	-DCMAKE_C_FLAGS="-I$NEWLIB_INC_PATH -fdeclspec -D__ELF__ -D_LIBUNWIND_IS_BAREMETAL=1 -D_LDBL_EQ_DBL -U__APPLE__ -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION -mcmodel=large" \
	-DCMAKE_LINKER="/usr/local/opt/llvm/bin/ld.lld" \
	-DCMAKE_SHARED_LINKER_FLAGS="-L${INSTALL_PREFIX}" \
	-DLIBCXXABI_USE_LLVM_UNWINDER=1 \
	-DLIBCXXABI_LIBUNWIND_PATH="$LIBUNWIND_PATH" \
	-DLIBCXXABI_LIBCXX_INCLUDES="$LIBCXX_INC_PATH" \
	-DLIBCXXABI_ENABLE_THREADS=False \
	-DLIBCXXABI_ENABLE_EXCEPTIONS=False \
	-DLIBCXXABI_TARGET_TRIPLE=x86_64-unknown-none-elf \
	-DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
	${SRC_ROOT} && \
make install
