#!/bin/bash -x
LIUMOS_THIRDPARTY_PATH=`pwd`/third_party
INSTALL_PREFIX=`pwd`/third_party_root

LLVM_BIN_PATH=/usr/local/opt/llvm/bin
NEWLIB_INC_PATH=${LIUMOS_THIRDPARTY_PATH}/newlib-cygwin_dest/include
LLVM_PROJ_PATH=${LIUMOS_THIRDPARTY_PATH}/llvm-project
LIBCXX_INC_PATH=$LLVM_PROJ_PATH/libcxx/include

SRC_ROOT=${LLVM_PROJ_PATH}/libcxx
BUILD_ROOT=${LIUMOS_THIRDPARTY_PATH}_build/libcxx
mkdir -p "$BUILD_ROOT" && cd "$BUILD_ROOT" &&
rm CMakeCache.txt ; cmake \
	-DCMAKE_AR=$LLVM_BIN_PATH/llvm-ar \
	-DCMAKE_CXX_COMPILER=$LLVM_BIN_PATH/clang++ \
	-DCMAKE_CXX_COMPILER_TARGET=x86_64-unknown-none-elf \
	-DCMAKE_CXX_FLAGS="-v -I$NEWLIB_INC_PATH -D__ELF__ -D_LIBUNWIND_IS_BAREMETAL=1 -D_LDBL_EQ_DBL -U__APPLE__ -D_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION -D_GNU_SOURCE -D_POSIX_TIMERS -mcmodel=large" \
	-DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
	-DCMAKE_C_FLAGS="-I$NEWLIB_INC_PATH -fdeclspec -D__ELF__ -D_LIBUNWIND_IS_BAREMETAL=1 -D_LDBL_EQ_DBL -U__APPLE__ -D_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION -D_GNU_SOURCE -D_POSIX_TIMERS -mcmodel=large" \
	-DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
	-DCMAKE_LINKER="/usr/local/opt/llvm/bin/ld.lld" \
	-DCMAKE_RANLIB=$LLVM_BIN_PATH/llvm-ranlib \
	-DCMAKE_SHARED_LINKER_FLAGS="-L${INSTALL_PREFIX}" \
	-DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
	-DLIBCXX_CXX_ABI=libcxxabi \
	-DLIBCXX_CXX_ABI_INCLUDE_PATHS="${LLVM_PROJ_PATH}/libcxxabi/include" \
	-DLIBCXX_CXX_ABI_LIBRARY_PATH="${LLVM_PROJ_PATH}/libcxxabi/build/lib" \
	-DLIBCXX_ENABLE_FILESYSTEM=False \
	-DLIBCXX_ENABLE_MONOTONIC_CLOCK=False \
	-DLIBCXX_ENABLE_RTTI=False \
	-DLIBCXX_ENABLE_SHARED=False \
	-DLIBCXX_ENABLE_STATIC=True \
	-DLIBCXX_ENABLE_THREADS=False \
	${SRC_ROOT} && \
make install
