#!/bin/bash -x
LIUMOS_THIRDPARTY_PATH=`pwd`/third_party
INSTALL_PREFIX=`pwd`/third_party_root

LLVM_BIN_PATH=/usr/local/opt/llvm/bin
NEWLIB_INC_PATH=${LIUMOS_THIRDPARTY_PATH}/newlib-cygwin_dest/include
LLVM_PROJ_PATH=${LIUMOS_THIRDPARTY_PATH}/llvm-project
LIBUNWIND_PATH=${LLVM_PROJ_PATH}/libunwind
LIBCXX_INC_PATH=$LLVM_PROJ_PATH/libcxx/include

COMMON_COMPILER_FLAGS="\
	-I$NEWLIB_INC_PATH \
	-fdeclspec -mcmodel=large \
	-D__ELF__ -U__APPLE__ \
	-D_LDBL_EQ_DBL -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION \
	" 

SRC_ROOT=${LLVM_PROJ_PATH}/libcxxabi
BUILD_ROOT=${LIUMOS_THIRDPARTY_PATH}_build/libcxxabi
mkdir -p "$BUILD_ROOT" && cd "$BUILD_ROOT" &&
rm CMakeCache.txt ; cmake \
	-DCMAKE_AR=$LLVM_BIN_PATH/llvm-ar \
	-DCMAKE_CXX_COMPILER=$LLVM_BIN_PATH/clang++ \
	-DCMAKE_CXX_FLAGS="$COMMON_COMPILER_FLAGS" \
	-DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
	-DCMAKE_C_FLAGS="$COMMON_COMPILER_FLAGS" \
	-DCMAKE_LINKER="/usr/local/opt/llvm/bin/ld.lld" \
	-DCMAKE_RANLIB=$LLVM_BIN_PATH/llvm-ranlib \
	-DCMAKE_SHARED_LINKER_FLAGS="-L${INSTALL_PREFIX}/lib" \
	-DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
	\
	-DLIBCXXABI_USE_LLVM_UNWINDER=1 \
	-DLIBCXXABI_LIBUNWIND_PATH="$LIBUNWIND_PATH" \
	-DLIBCXXABI_LIBCXX_INCLUDES="$LIBCXX_INC_PATH" \
	-DLIBCXXABI_ENABLE_THREADS=False \
	-DLIBCXXABI_ENABLE_EXCEPTIONS=False \
	-DLIBCXXABI_TARGET_TRIPLE=x86_64-unknown-none-elf \
	-DLIBCXXABI_ENABLE_SHARED=False \
	-DLIBCXXABI_ENABLE_STATIC=True \
	\
	-DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
	${SRC_ROOT} && \
make install
